Repository C2Devel/aws-sdk-go, pull requests merged in 2024-11, with the labels that each got.

#27 protocol: add ec2query errors unmarshaling for query protocol
  private/protocol/query/unmarshal_error.go
  private/protocol/query/unmarshal_error_test.go
Labels: fixup

#35 update iam api
  models/apis/iam/2010-05-08/api-2.json
  service/iam/api.go
  service/iam/examples_test.go
  service/iam/iamiface/interface.go
Labels: need description

#37 paas: add name for service and instance endpoints
  models/apis/paas/2022-09-06/api-2.json
  service/paas/api.go
Labels: bug
